### ISSUE TITLE
Some stations not getting EPG

### ISSUE THREAD

**Issue by AnneWielis** [DeBaschdi/service.takealug.epg-grabber#18]
Sorry, if that is answered elsewhere...some stations don't seem to get EPG Data, although activated in the plugin.

How exactly is the mapping working?

![grafik](https://user-images.githubusercontent.com/41674213/213261101-4e64bef7-5000-4b3b-82bb-2ec6549a7a20.png)
![grafik](https://user-images.githubusercontent.com/41674213/213261277-2a9bea1d-06e7-4def-bb74-3d08177f34af.png)

Any help appreciated ;-)

**Comment by dadav** [comment]
As far as I know this could be because of an invalid tvg-id name in your m3u file.

Mine looks like this:

`#EXTINF:0 tvg-id="ARD.de",Das Erste HD`

**Comment by AnneWielis** [comment]
So the tvg-id in the Station Information is the reference key? What information in the grabbed EPG does it have to map?

**Comment by dadav** [comment]
Exactly, `tvg-id` has to match the channel in your guide.xml file. It should look like this:

```xml
<channel id="ARD.de">
...
</channel>
```

**Comment by AnneWielis** [comment]
So i have to either patch the channel m3u (which currently comes from http://bit.ly/kn-kodi-tv ) or the guide.xml after downloading, right? I hoped there was some method to tweak the matching process itself.

**Comment by dadav** [comment]
> So i have to either patch the channel m3u (which currently comes from http://bit.ly/kn-kodi-tv ) or the guide.xml after downloading, right? I hoped there was some method to tweak the matching process itself.

Yeah...I think currently this is the only way. I'm doing it by modifying the m3u file and hosting it in a github repository.

**Comment by AnneWielis** [comment]
OK, thanks so much for clarifying that.
