### ISSUE TITLE
Missing HD channels

### ISSUE THREAD

**Issue by damnms** [DeBaschdi/service.takealug.epg-grabber#6]
90% of my channels are HD (like ARD HD). I was unable to find those. Would it be possible to somehow add all existing regular german channels including their HD version?
I am not sure if its somehow possible to tell iptv.simple to use "ARD" if "ARD HD" is not available... guess not

**Comment by DeBaschdi** [comment]
If you use iptvsimple, you need to assign your guide channels(challel_id in .xml) to match the tvg-id's in your .m3u, edit your .m3u and and it should work.

**Comment by damnms** [comment]
editing the .m3u is a very bad idea i guess, because its provided by the ISP. that means: when a channel is modified, added or deleted, i would not notice that when i download that file and modify it with e.g. sed.

even worse: i would not know anymore which channel is HD and which not... 

edit #2: its different. the ID of my provider for e.g. SRF1 is SRF1, whereas in your EPG xml it is "srf1.ch" - same or equivalent to all other channels. why is that? who defines that id? the only workaround i can imagine right now is to create a cronjob that replaces all those occurances of e.g. "srf1.ch" to "srf1" in the epg .xml

edit #3: i just checked the .m3u, there it says: tvg-name="SRF2.ch"
thats the only "id" i could find, nothing with "srfzwei", so i am very curious if its even possible to change the .m3u so that the epg .xml matches
i compared the .xml with the one that was working https://github.com/mathewmeconry/TV7_EPG_Data/ and i am really wondering who or where those IDs are defined.

**Comment by DeBaschdi** [comment]
Mein Grabber nutzt per default das genormte channelid format rytec, wenn du das nicht willst, stell das Format auf provider, dann wird aus srf1.ch SRF1 oder srf1, oder Srf1, kommt dann eben auf den Provider drauf an wie er seine Kanäle nennt (abzuraten).
Im jedem Fall, da sich dein iptv Anbieter nicht an Norm hällt musst du deine .m3u editieren, per skript oder sonst wie um die ids identisch zu machen.

Schau dir mal tvheadend an, das sollte mit jeder Konstellation umgehen, im webif können die kanäle dem xml einfach zugeordnet werden.

Ps, es ist pups egal ob der kanal hd ist oder nicht, das epg ist identisch, auf hd läuft nichts anderes.
Einfach srf1.ch als id für SRF1 und SRF1 HD nehmen (doppel zuordnung)

Du findest mich auf Kodinerds.net
LG

**Comment by damnms** [comment]
jo danke, muss mir das mal genau anschauen... ich kenn mich damit halt echt 0 aus, hab dieses "fertige" .xml immer von dem repo (mathewmeconry) gezogen per cronjob und das hat gefunzt... waeren in kuerze nicht bald pruefungen, wuerd ich mir das mal echt in ruhe paar tage reinziehen ;) 
auf tvheadend wollte ich auch schon wechseln, aber noch keine zeit dazu gehabt.

mir ist schon klar dass das signal (bzw. die qualitaet) absolut egal ist, aber damit aendert sich eben die ID, und das fuehrt zu problemen. ich glaub als erster workaround koennte das format rytec->provider passen, wenns so funzt... waere wohl die einfachste/schnellste loesung - danke!
